fix: Upgrading restify to fix error on Node version 18+
Current version leads to the following error on Node 18+:

➜  my-echo-bot npm start

> my-echo-bot@1.0.0 start
> node ./index.js

/home/gregborrelly/development/myJsBots/my-echo-bot/node_modules/restify/lib/request.js:848
    Request.prototype.closed = function closed() {
                             ^

TypeError: Cannot set property closed of #<Readable> which has only a getter
    at patch (/home/gregborrelly/development/myJsBots/my-echo-bot/node_modules/restify/lib/request.js:848:30)
    at Object.<anonymous> (/home/gregborrelly/development/myJsBots/my-echo-bot/node_modules/restify/lib/server.js:33:1)