Type definition fix: OAuthPromptState
Fixed for error related to issue 1155 
node_modules/botbuilder-dialogs/src/prompts/oauthPrompt.ts(161,17): error TS7053: Element implicitly has an 'any' type because expression of type '"attemptCount"' can't be used to index type '{}'.
  Property 'attemptCount' does not exist on type '{}'.